%YAML 1.1
---
language: python
python:
  - 2.7
  - pypy
  - 3.4
before_install:
  - pip install codecov
install:
  - pip install -r test-requirements.txt
  - pip install -e .
script: nosetests
after_success:
  - codecov
